### ISSUE TITLE
FreeIPA

### ISSUE THREAD

**Issue by woopstar** [AppliedTrust/goklp#5]
I'm trying to set this up with FreeIPA, but somehow it does not return any keys when using:
```
goklp_ldap_uri             = ldaps://server
goklp_ldap_base_dn         = cn=users,cn=accounts,dc=domain,dc=com
goklp_ldap_bind_dn         = uid=bind,cn=sysaccounts,cn=etc,dc=domain,dc=com
goklp_ldap_bind_pw         = secret
goklp_ldap_timeout_secs    = 5
goklp_debug                = true
goklp_insecure_skip_verify = false
```

**Comment by disassembler** [comment]
Is your ssl cert issued by a trusted ca? Do you get the same result if you set goklp_insecure_skip_verify? Is the username in the uid field?

**Comment by woopstar** [comment]
Fixed by https://github.com/pasientskyhosting/goklp/commit/ac80d39f86209b134a9e7be4700d53848e781978

Issue was that freeIPA is not using sshPublicKey as attribute
